kind: List
apiVersion: v1
metadata: {}
items:
- apiVersion: v1
  kind: Template
  metadata:
    name: apache-kafka
    annotations:
      description: 1-pod Apache Kafka
      tags: messaging,streaming,kafka
    labels:
      app: apache-kafka
  parameters:
  - name: NAME
    description: Name prefix for each object created
    required: true
    value: apache-kafka
  - name: IMAGE
    description: Image with Apache Kafka and Apache ZooKeeper
    required: true
    value: rondinif/openshift-kafka
  objects:

## PERSISTENT VOLUMES
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-apache-kafka
      labels: 
        app: apache-kafka
        StorageType: ENDURANCE
    spec:
      capacity:
        storage: 500MB
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: default
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-apache-zookeeper
      labels: 
        app: apache-kafka
        StorageType: ENDURANCE
    spec:
      capacity:
        storage: 500MB
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: default
      
  ## PERSISTENT VOLUME CLAIMS
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: apache-kafka
      name: apache-kafka
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 500MB
      storageClassName: default
      volumeName: pv-apache-kafka
    selector: 
      matchLabels:
        app: apache-kafka
    status:
      phase: Pending
  
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: apache-kafka
      name: apache-zookeeper
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 500MB
      storageClassName: default
      volumeName: pv-apache-zookeeper
    status:
      phase: Pending

## DEPLOYMENT CONFIG
    - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
      labels:
        app: apache-kafka
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
            app: apache-kafka
        spec:
          hostname: ${NAME}
          containers:
          - name: apache-kafka
            image: ${IMAGE}
            command:
            - bin/kafka-server-start.sh
            args:
            - config/server.properties
            - --override
            - advertised.host.name=${NAME}
            - --override
            - log.segment.bytes=10485760
            - --override
            - log.retention.bytes=10485760
            volumeMounts:
            - mountPath: /tmp/kafka-logs
              name: kafka-logs
            ports:
            - containerPort: 9092
          - name: apache-zookeeper
            image: ${IMAGE}
            command:
            - bin/zookeeper-server-start.sh
            args:
            - config/zookeeper.properties
            volumeMounts:
            - mountPath: /tmp/zookeeper
              name: zookeeper
            ports:
            - containerPort: 2181
          volumes:
          - name: zookeeper
#            emptyDir: {}
            persistentVolumeClaim:
              claimName: apache-zookeeper
          - name: kafka-logs
#            emptyDir: {}
            persistentVolumeClaim:
              claimName: apache-kafka
  
  ## SERVICE
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: apache-kafka
      name: ${NAME}
    spec:
      ports:
      - name: kafka
        port: 9092
      - name: zookeeper
        port: 2181
      selector:
        deploymentconfig: ${NAME}
