kind: List
apiVersion: v1
metadata: {}

items:

- apiVersion: v1
  kind: Template
  metadata:
    name: apache-kafka3
    annotations:
      description: 1-pod Apache Kafka
      tags: messaging,streaming,kafka
  parameters:
  - name: NAME
    description: Name prefix for each object created
    required: true
    value: apache-kafka3
  - name: IMAGE
    description: Image with Apache Kafka and Apache ZooKeeper
    required: true
    value: rondinif/openshift-kafka
  objects:
  #
  - apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
  #  annotations:
  #    ibm.io/provisioning-status: complete
  #    pv.kubernetes.io/bind-completed: "yes"
  #    pv.kubernetes.io/bound-by-controller: "yes"
  #    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-file
  #  creationTimestamp: null
  #  finalizers:
  #  - kubernetes.io/pvc-protection
  #  labels:
  #    region: us-east
  #    zone: wdc04
    name: apache-kafka-storage
  #  selfLink: /api/v1/namespaces/ibm-demo-app/persistentvolumeclaims/apache-kafka-storage
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 500M
    storageClassName: default
#    volumeName: pv-apache-kafka
 # 
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          hostname: ${NAME}
          containers:
          - name: apache-kafka3
            image: ${IMAGE}
            command:
            - bin/kafka-server-start.sh
            args:
            - config/server.properties
            - --override
            - advertised.host.name=${NAME}
            - --override
            - log.segment.bytes=10485760
            - --override
            - log.retention.bytes=10485760
            volumeMounts:
            - mountPath: /tmp/kafka-logs
              name: kafka-logs
            ports:
            - containerPort: 9092
          - name: apache-zookeeper
            image: ${IMAGE}
            command:
            - bin/zookeeper-server-start.sh
            args:
            - config/zookeeper.properties
            volumeMounts:
            - mountPath: /tmp/zookeeper
              name: zookeeper
            ports:
            - containerPort: 2181
          volumes:
          - name: kafka-logs
          persistentVolumeClaim:
            claimName: apache-kafka-storage
          - name: zookeeper
            emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
      - name: kafka
        port: 9092
      - name: zookeeper
        port: 2181
      selector:
        deploymentconfig: ${NAME}
