kind: List
apiVersion: v1
metadata: {}
items:
- apiVersion: v1
  kind: Template
  metadata:
    name: apache-kafka2
    annotations:
      description: 1-pod Apache Kafka
      tags: messaging,streaming,kafka
    labels:
      app: apache-kafka2
  parameters:
  - name: NAME
    description: Name prefix for each object created
    required: true
    value: apache-kafka2
  - name: IMAGE
    description: Image with Apache Kafka and Apache ZooKeeper
    required: true
    value: jhusak/apache-kafka
  objects:
 
## DEPLOYMENT CONFIG
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
      labels:
        app: apache-kafka2
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
            app: apache-kafka2
        spec:
          hostname: ${NAME}
          containers:
          - name: apache-kafka2
            image: ${IMAGE}
            command:
              - /bin/sh
              - '-c'
            args:
              - >-
                echo JH starting;  rm /tmp/kafka-logs/.lock 2>/dev/null;
                bin/kafka-server-start.sh config/server.properties --override
                advertised.host.name=apache-kafka2 --override
                log.segment.bytes=10485760 --override log.retention.bytes=10485760;
            volumeMounts:
            - mountPath: /tmp/kafka-logs
              name: kafka-logs2
            ports:
            - containerPort: 9092
          - name: apache-zookeeper2
            image: ${IMAGE}
            command:
            - bin/zookeeper-server-start.sh
            args:
            - config/zookeeper.properties
            volumeMounts:
            - mountPath: /tmp/zookeeper
              name: zookeeper2
            ports:
            - containerPort: 2181
          volumes:
          - name: zookeeper2
            persistentVolumeClaim:
              claimName: apache-kafka
          - name: kafka-logs2
            persistentVolumeClaim:
              claimName: apache-kafka
  
  ## SERVICE
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: apache-kafka2
      name: ${NAME}
    spec:
      ports:
      - name: kafka
        port: 9092
      - name: zookeeper
        port: 2181
      selector:
        deploymentconfig: ${NAME}
